Feature app
acushlakoncept/micro-reddit pull request #1
Opened 2020-07-28 14:48 UTC by somoye123

Implement data structures necessary to support link submissions and commenting on Reddit

2020-07-28 17:09 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thanks for the effort put in this project.
However, there are some issues.
Please, read the comment below. I suggest you use `rails console` to test the validity of object create from your model.

Once done, submit a new code review request.
Thanks

Mael FOSSO

2020-07-28 17:09 UTC, maelfosso commented on app/models/post.rb
> +  validates :user_id, presence: true
Kindly change `:user_id` by `:user` to make it works.

2020-07-28 17:09 UTC, maelfosso commented on app/models/comment.rb
> +  validates :post_id, presence: true
Kindly directly use `:user` and `:post` to make it works

2020-07-28 18:46 UTC, uryelah commented
Hi **Somoye Somoye & Uduak Essien**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with the fixes guys!

On an [Optional] note, why don't you have a bit more fun with the validations? 
- [ ] Try to validate if the email string is actually in the email format, you can use both regular expressions or rails inbuilt classes for that
- [ ] Validate the length of the body and title
- [ ] Validate the password so it's strong enough, can you make sure it's at least 6 characters, has letters and numbers and at least one symbol?

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being awesome devs and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-07-28 18:46 UTC, uryelah approved these changes
Hi **Somoye Somoye & Uduak Essien**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with the fixes guys!

On an [Optional] note, why don't you have a bit more fun with the validations? 
- [x] Try to validate if the email string is actually in the email format, you can use both regular expressions or rails inbuilt classes for that
- [x] Validate the length of the body and title
- [x] Validate the password so it's strong enough, can you make sure it's at least 6 characters, has letters and numbers and at least one symbol?

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being awesome devs and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-07-28 21:59 UTC, merged

2020-07-29 08:06 UTC, acushlakoncept commented
> Hi **Somoye Somoye & Uduak Essien**, I'm Sarah your reviewer for this PR 👩‍🚀
> 
> Good job with the fixes guys!
> 
> On an [Optional] note, why don't you have a bit more fun with the validations?
> 
> * [x]  Try to validate if the email string is actually in the email format, you can use both regular expressions or rails inbuilt classes for that
> * [x]  Validate the length of the body and title
> * [x]  Validate the password so it's strong enough, can you make sure it's at least 6 characters, has letters and numbers and at least one symbol?
> 
> ## **Your project is approved! 🎊 🥅 💛**
> **You may close this Pull Request and merge the changes**
> 
> **Keep being awesome devs and good luck with your next project!**
> 
> Cheers and Happy coding!👏👏👏
> 
> Code review by **Sarah Uryelah Silva Chamorro**
> 
> (Feel free to contact me on slack by the handle of **sarah** if you have any additional question)

Thank you, we've implemented the requested optional validations.